[database]
host   = "localhost"
port   = "5432"
database = "lys_test"
schemaCreationOrder = ["public", "core"] # must be updated when schemas are added / removed. Also need to add to schemas.sql

[dbSuperUser]
userName = "postgres"
password = ""

[dbOwnerUser]
userName = "lys_owner" # this PG user owns all database objects
password = "123"
